tracee/tracee

binding/cxf/src/main/java/io/tracee/binding/cxf/TraceeCxfFeature.java, binding/cxf/src/test/java/io/tracee/binding/cxf/CxfClientToCxfServerIT.java, binding/cxf/src/test/java/io/tracee/binding/cxf/CxfClientToJaxwsServerIT.java, binding/cxf/src/test/java/io/tracee/binding/cxf/JaxwsClientToCxfServerIT.java, binding/cxf/src/test/java/io/tracee/binding/cxf/TraceeCxfFeatureTest.java
Remove the middle package `client` for the CXF-Feature. This feature is able to handle clients and server implementations.
=> Move ApacheCXF feature to root of cxf package

api/src/main/java/io/tracee/TraceeBackend.java, core/src/main/java/io/tracee/MDCLikeTraceeBackend.java, core/src/test/java/io/tracee/MDCLikeTraceeBackendTest.java, testhelper/src/main/java/io/tracee/SimpleTraceeBackend.java
The `TraceeBackend`-Class provides two helper methods. One to retrieve the request-id, one for the session-id. -- of course only if present in the backend.
For example: `Tracee.getBackend().getSessionId()` is just a shortcut for `Tracee.getBackend().get(TraceeConstants.SESSION_ID_KEY)`
=> Add shortcut to requestId and sessionId

binding/springmvc/src/main/java/io/tracee/binding/springmvc/TraceeInterceptor.java, binding/springmvc/src/test/java/io/tracee/binding/springmvc/TraceeInterceptorTest.java
This PR cleans the backend (later) in the 'afterCompletion'-Phase of the spring mvc interceptor.
I'm not sure but this may fix our issue that some logmessages are without tracee keys. My current explaination: We clean the context to early and the log-message hasn't be created by slf4j/logback - some lazy/async behavior?.
=> SpringMVC: Clear tracee backend in afterCompletion phase

core/pom.xml, core/src/main/java/io/tracee/MDCLikeTraceeBackend.java, core/src/main/java/io/tracee/configuration/PropertiesBasedTraceeFilterConfiguration.java, core/src/test/java/io/tracee/MDCLikeTraceeBackendTest.java, core/src/test/java/io/tracee/configuration/PropertiesBasedTraceeFilterConfigurationBenchmarkTest.java, core/src/test/java/io/tracee/configuration/PropertiesBasedTraceeFilterConfigurationTest.java, pom.xml
Due caching of property filtering configuration we could skip string tokenizing and regex compilation and use a LRU cache instead.
With 2000000 filterings in a simple microbenchmark:
Pattern .* (permit all): old: 2seconds, new: 1,4seconds
Pattern tracee.* (permit keys prefixed with 'tracee'): Old: 5,8secs, new: 2,8secs
=> Speedup property filtering

binding/cxf/pom.xml, binding/cxf/src/main/java/io/tracee/binding/cxf/interceptor/AbstractTraceeInInterceptor.java, binding/cxf/src/main/java/io/tracee/binding/cxf/interceptor/AbstractTraceeOutInterceptor.java, binding/cxf/src/test/java/io/tracee/binding/cxf/interceptor/IncomingRequestMessageTest.java, binding/cxf/src/test/java/io/tracee/binding/cxf/interceptor/IncomingRequestSoapMessageTest.java, binding/cxf/src/test/java/io/tracee/binding/cxf/interceptor/OutgoingMessageTest.java, binding/cxf/src/test/java/io/tracee/binding/cxf/interceptor/OutgoingSoapMessageTest.java
There is a constant value attached to the exchange if the type of the message is a REST message. Instead of the class, I check for the value in the hashmap.
Found the approach a few weeks ago in a CXF discussion as workaround, so I think it's the best practise how we can solve this.
=> First approach to fix issue #106

api/src/main/java/io/tracee/BackendProviderResolver.java, core/src/test/java/io/tracee/backend/slf4j/Slf4jTraceeBackendIT.java
If no backend can determined by SPI, the default SLF4J backend is used. But in this case the lookup and initialization (`Class.forName(..)`) takes place by every invocation. This PR adds the Slf4J backend to the cache. The cache-key is the current classloader.
=> Add Slf4J backend to cache

binding/cxf/src/main/java/io/tracee/binding/cxf/interceptor/AbstractTraceeInInterceptor.java, binding/cxf/src/main/java/io/tracee/binding/cxf/interceptor/AbstractTraceeOutInterceptor.java
This could also be a problem if a developer create manual boolean instances (`new Boolean(true)`). In this case the previous comparison won't work!
=> Use equals instead of the equal sign. Fixes coverity.

api/src/test/java/io/tracee/TraceeTest.java, binding/cxf/src/test/java/io/tracee/binding/cxf/interceptor/IncomingRequestMessageTest.java, pom.xml
adds javac compiler arguments to maven-compiler-plugin to treat java warnings as errors
=> treat javac warnings as errors

core/src/test/java/io/tracee/BackendBaseTest.java, core/src/test/java/io/tracee/backend/slf4j/Slf4jMdcDelegationTest.java
`BackendBaseTest` is testing alot of stuff of the `BackendBaseTest.TestBackend` class. This is kind of stupid: We're testing testcode that is only used in this test.
I've moved several testcases to test the `Slf4jTraceeBackend` and replaced the `TestBackend` with a simple Spy to test the abstract implementation, f.e. the configuration handling.
=> Testrefactoring of BackendBaseTest

binding/cxf/pom.xml, core/pom.xml, pom.xml
Put logback to the scope 'test' because it's only needed for some tests
=> Resolve #131: Logback dependency in test-scope

binding/jaxrs2/src/main/java/io/tracee/binding/jaxrs2/TraceeClientFilter.java, binding/jaxrs2/src/main/java/io/tracee/binding/jaxrs2/TraceeContainerFilter.java
This PR removes the final modifiers from the filter methods of TraceeClientFilter.java and TraceeContainerFilter.java in the jaxrs2 binding.
=> Remove final modifiers for #134

README.md, backend/threadlocal-store/README.md, binding/cxf/README.md, binding/httpclient/README.md, binding/httpcomponents/README.md, binding/jaxrs2/README.md, binding/jaxws/README.md, binding/jms/README.md, binding/quartz/README.md, binding/servlet/README.md, binding/springhttpclient/README.md, binding/springmvc/README.md, binding/springrabbitmq/README.md, binding/springws/README.md, bom/README.md
Use concret version in the documentation to be compatible with Maven 3.
We strongly suggest to create a version property. Due the limitation of markdown properties we point to the property `tracee.version` in the module documentations.
=> Use concret version in the markdown documentation

binding/jms/pom.xml, binding/jms/src/main/java/io/tracee/binding/jms/TraceeMessageListener.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeMessageListenerTest.java
Please refer to [this issue](https://github.com/tracee/tracee/issues/140) for detail
For TraceeMessageListenerTest, I didn't quite understand why there was an context content assertion in MdbLike. I thought it was used to assert the mdb being invoked successfully. So I changed this part.
=> #140-Generate InvocationId if no TPIC property in javax.jms.Message

.travis.yml, api/pom.xml, backend/threadlocal-store/pom.xml, binding/cxf/pom.xml, binding/httpclient/pom.xml, binding/httpcomponents/pom.xml, binding/jaxrs2/pom.xml, binding/jaxws/pom.xml, binding/jms/pom.xml, binding/quartz/pom.xml, binding/servlet/pom.xml, binding/springhttpclient/pom.xml, binding/springmvc/pom.xml, binding/springrabbitmq/pom.xml, binding/springws/pom.xml, bom/pom.xml, core/pom.xml, pom.xml, testhelper/pom.xml
Initial commit for TracEE 2.0
* Raise the version up to 2.0.0-SNAPSHOT
* Use Java7 instead of Java6.
=> Resolve #129: Use Java7 in TracEE 2.0

binding/httpclient/pom.xml, binding/httpcomponents/pom.xml, binding/servlet/pom.xml, binding/servlet/src/test/java/io/tracee/binding/servlet/TraceeFilterIT.java, binding/servlet/src/test/java/io/tracee/binding/servlet/TraceeServletRequestListenerTest.java, binding/springhttpclient/pom.xml, binding/springmvc/pom.xml, binding/springmvc/src/test/java/io/tracee/binding/springmvc/TraceeInterceptorTest.java, binding/springws/pom.xml, pom.xml
Let's move to Servlet-API 3.0 and Jetty 8.
In TracEE 1.x different Jetty versions have been used in different modules. With this PR I've added a variable in the parent pom and extracted the `jetty-servlet` dependency definition.
=> TracEE 2: Upgrade Jetty to 8.1.x and use the same version in all TracEE modules

pom.xml
Use the latest version of the legecy Log4J (1.2.17) and the newest one of Log4J2 (they release so often, when we'll release TracEE 2.0 this will be an old one ;-) ).
Both are still compatible to their major versions.
=> TracEE 2: Upgrade to the latest Log4J versions

binding/quartz/README.md, binding/quartz/pom.xml, binding/quartz/src/main/java/io/tracee/binding/quartz/TraceeContextInjector.java, binding/quartz/src/main/java/io/tracee/binding/quartz/TraceeJobListener.java, binding/quartz/src/test/java/io/tracee/binding/quartz/TraceeContextInjectorTest.java, binding/quartz/src/test/java/io/tracee/binding/quartz/TraceeJobListenerIT.java, binding/quartz/src/test/java/io/tracee/binding/quartz/TraceeJobListenerTest.java
I've checked the listeners for a better integration in case of writing the jobs to the queue. But nothing have changed: Modified jobs aren't saved again into the queue, so the TPIC is lost if the queue isn't stored locally / inmemory.
=> TracEE 2: Reworked the quartz module. Updated quartz to 2.2.2

binding/httpcomponents/README.md, binding/httpcomponents/pom.xml, binding/httpcomponents/src/test/java/io/tracee/binding/httpcomponents/TraceeHttpInterceptorsIT.java
The used version of `httpcomponents` was antiquated and in the meanwhile the usage of the `HttpClient` has changed. With this PR a newer version of the httpcomponent library is used. I've adapted the test code and the documentation how the interceptors are added.
Regarding the interceptor order: I think it's great to be the last interceptor due request time but the first handling the response. So other request interceptors are able to add additional tracee values.
=> Small update of httpcomponents

core/src/main/java/io/tracee/backend/slf4j/Slf4jTraceeBackend.java
Look into the MDC class of SLF4J: The `IllegalArgumentException` is also an unchecked exception but they promote the exception on API level by adding `throws IllegalArgumentException`.
Some static code analytic tools doesn't like a manual thrown NPE, so why not replace the NPE with the `IllegalArgumentException`?
=> Throw IllegalArgumentException like MDC of slf4j instead of a NPE

binding/README.md, binding/httpcomponents5/README.md, binding/httpcomponents5/pom.xml, binding/httpcomponents5/src/main/java/io/tracee/binding/httpcomponents/TraceeHttpRequestInterceptor.java, binding/httpcomponents5/src/main/java/io/tracee/binding/httpcomponents/TraceeHttpResponseInterceptor.java, binding/httpcomponents5/src/test/java/io/tracee/binding/httpcomponents/TraceeHttpInterceptorsIT.java, binding/httpcomponents5/src/test/java/io/tracee/binding/httpcomponents/TraceeHttpRequestInterceptorTest.java, binding/httpcomponents5/src/test/java/io/tracee/binding/httpcomponents/TraceeHttpResponseInterceptorTest.java, pom.xml
The alpha1 of [Apache HttpComponents 5](https://hc.apache.org/httpcomponents-client-5.0.x/index.html) has been released in January 2016. The new version of the library has a new package structure and a different maven identifier so our module for httpcomponents 4 doesn't fit.
WDYT?
=> add new module for httpcomponents 5

binding/jms/src/main/java/io/tracee/binding/jms/TraceeMessageListener.java, binding/jms/src/main/java/io/tracee/binding/jms/TraceeMessageProducer.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeMessageListenerAndProducerIT.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeMessageListenerTest.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeMessageProducerTest.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeQueueSenderTest.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeTopicPublisherTest.java
Websphere 12c doesn't allow Map as JMS header payload. Fix: We render the TPIC as string.
=> Fixes #168: Change JMS header (Tracee 2.0)

binding/jms/src/main/java/io/tracee/binding/jms/TraceeMessageListener.java, binding/jms/src/main/java/io/tracee/binding/jms/TraceeMessageProducer.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeMessageListenerAndProducerIT.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeMessageListenerTest.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeMessageProducerTest.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeQueueSenderTest.java, binding/jms/src/test/java/io/tracee/binding/jms/TraceeTopicPublisherTest.java
Websphere 12c doesn't allow Map as JMS header payload. Fix: We render the TPIC as string.
(cherry picked from commit c7c0a64)
=> Fixes #168: Change JMS header (Tracee 1.x)

api/README.md
Remove references to old backends and precise the information what a …developer of own backend can expect / has to keep in mind.
=> Fixes #171: Remove backend references in the documentation
